Traceback (most recent call last):
  File "/home/mpirtgod/PycharmProjects/AdvancePython/mod5/TestsTask4.py", line 11, in test_stdout_file
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
